### ISSUE TITLE
SSIM is much lower!

### ISSUE THREAD

**Issue by p4r4mount** [ercanburak/EVREAL#3]
Thanks for the great work! I ran the std evaluation code but got different results with the paper.
The MSE and LPIPS values align with those reported in the paper, but the SSIM values obtained are significantly lower. I would like to know if additional parameter settings or other reasons are causing this discrepancy. The result is shown in the following fig.
![1](https://github.com/ercanburak/EVREAL/assets/56263732/2a9b5354-840f-47f6-a15c-161ac66cd9f7)

**Comment by ercanburak** [comment]
Hi @p4r4mount, and thank you for your interest in our work!

You are right; the SSIM scores generated with the latest code in this repo are different than those reported in the paper. This is because we made a small change in the code (in this commit 68b13a7, after the paper was published) regarding how the SSIM values are calculated. Now, the correct range of pixel values is considered during the calculations. You can see [here](https://github.com/scikit-image/scikit-image/commit/ff699a56eec0e433e890220f95ba073a388fc714) for more details about the reason for this change.

Please note that this applies to the SSIM scores of all methods, without affecting the rankings much. Therefore, the conclusions we draw from the scores are not changing. We are planning to submit a new version of the paper to arXiv, including these updated SSIM scores.

**Comment by p4r4mount** [comment]
Thank you for your response!  It's very helpful to me.
